### ISSUE TITLE
v2.1.2+1 fails to compile with flutter v2.2.2

### ISSUE THREAD

**Issue by oysterpack** [Nolence/async_button_builder#20]
> async_button_builder-2.1.2+1/lib/src/async_button_builder.dart:355:25: Error: Required named parameter 'vsync' must be provided.
> /flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.

My flutter env is:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)
```

**Comment by Nolence** [comment]
My bad, currently I've been compiling against dev which doesn't require the vsync property on `AnimatedSize`. A quick fix will be to override the version you use to `2.1.2` instead of latest.

As this is no longer a personal project I'll start building against stable to better suit more users. Will update soon

**Comment by Nolence** [comment]
Test and builds against stable now 1a9f08cf5d29f261170cb295067cd13350473a5d

Try `^2.1.3`

**Comment by oysterpack** [comment]
thanks for the quick fix
